# Generated by Django 4.1 on 2022-09-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0002_posts_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post',
            new_name='posteo',
        ),
    ]
