# Generated by Django 4.1 on 2022-09-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0003_rename_post_posts_posteo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='abstract',
            new_name='equipo',
        ),
    ]
