# Generated by Django 4.1 on 2022-09-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0004_rename_abstract_posts_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='articulothumb',
            new_name='posteothumb',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
