# Generated by Django 4.1.1 on 2022-09-30 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0005_rename_articulothumb_thumbnail_posteothumb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-creado']},
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
