# Generated by Django 4.1 on 2022-09-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0006_alter_posts_options_delete_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='thumbnail',
            old_name='image',
            new_name='imagen',
        ),
    ]
