# Generated by Django 4.1 on 2022-09-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0007_rename_image_posts_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='thumbnail',
            old_name='imagen',
            new_name='image',
        ),
    ]
