# Generated by Django 4.1 on 2022-09-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0008_rename_imagen_posts_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
