# Generated by Django 4.1.1 on 2022-09-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0009_alter_posts_image_alter_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
