# Generated by Django 4.1.1 on 2022-10-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0010_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
