# Generated by Django 4.1.1 on 2022-10-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0011_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='AppWT/thumbnail/'),
        ),
    ]
