# Generated by Django 4.1.1 on 2022-10-03 22:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0014_rename_equipo_posts_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('subtitulo', models.CharField(max_length=1280)),
                ('posteo', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='subtitulo',
            field=models.CharField(max_length=1280),
        ),
    ]
