# Generated by Django 4.1.1 on 2022-10-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWT', '0015_ourselection_alter_posts_subtitulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurSelection',
        ),
    ]
